databases:
  - name: hotel-system-db
    plan: free
    databaseName: hotel_system
    user: hotel_system

services:
  - type: web
    name: hotel-system
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: python -m gunicorn hotel_system.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-system-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
