# Generated by Django 6.0.5 on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='recipt',
            new_name='receipt',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Approved', 'Approved'),
                    ('Rejected', 'Rejected'),
                    ('Cancelled', 'Cancelled'),
                ],
                default='Pending',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='booking',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='Receipt_Img/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
